name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      # Клонируем репозиторий
      - name: Checkout
        uses: actions/checkout@v4

      # Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Включаем Corepack (для Yarn Berry)
      - name: Enable Corepack
        run: corepack enable

      # Установка зависимостей RN
      - name: Install JS dependencies
        run: yarn install

      # Установка CocoaPods
      - name: Install Pods
        run: |
          cd ios
          pod install

      # Сборка приложения
      - name: Build iOS app
        run: |
          cd ios
          xcodebuild \
            -workspace Todorant.xcworkspace \
            -scheme Todorant \
            -configuration Release \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO \
            -derivedDataPath build

      # Создание IPA
      - name: Create IPA
        run: |
          mkdir Payload
          cp -R ios/build/Build/Products/Release-iphoneos/Todorant.app Payload/
          zip -r Todorant.ipa Payload

      # Загрузка артефакта
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: Todorant-ipa
          path: Todorant.ipa
