name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Устанавливаем Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Ставим Yarn classic
      - name: Install Yarn classic
        run: |
          npm install -g yarn@1

      - name: Install JS dependencies
        run: yarn install --frozen-lockfile

      # Устанавливаем pods
      - name: Install CocoaPods
        run: |
          cd ios
          pod install

      # Сборка iOS
      - name: Build iOS
        run: |
          cd ios
          xcodebuild \
            -workspace *.xcworkspace \
            -scheme Todorant \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGNING_ALLOWED=NO \
            -derivedDataPath build

      # Создание IPA
      - name: Create IPA
        run: |
          mkdir Payload
          cp -R ios/build/Build/Products/Release-iphoneos/*.app Payload/
          zip -r app.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ipa
          path: app.ipa
